--- #YAML:1.0
name:               String-Similarity-Group
version:            1.05
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1
    Cwd:                  3
    Exporter:             5
    Getopt::Std::Strict:  1.01
    String::Similarity:   1.02
    Test::Simple:         0
    YAML:                 0.66
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
